### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by marin117** [marin117/Gmail-deleter#7]
Add command line progress bar.

https://stackoverflow.com/questions/3173320/text-progress-bar-in-the-console

**Comment by adilhussain540** [comment]
@marin117 - The accepted answer on that link makes use of the code that requires us to have an exact `count` of data. As far as I've seen the codebase, we are iterating over `generators` not `lists`.
But we can still use the [tqdm](https://pypi.org/project/tqdm/) for some improvements. It does show the time elapsed, total iterations, etc.
Let me know what you think.

**Comment by marin117** [comment]
Sure. Feel free to implement and create a PR. If everything is working I will approve it :)
